baseurl: ""
permalink: /blog/:year/:month/:title
#wget -m http://project.oldmapsonline.org/collections

markdown: rdiscount
gems:
    - jekyll-redirect-from
prose:
  rooturl: "_posts"
  siteurl: "http://prose.github.io/starter/"
  relativeLinks: "http://prose.github.io/starter/links.jsonp"
  media: "media"
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "OldMapsOnline"
              value: "OldMapsOnline"