baseurl: ""

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title


plugins:
    - jekyll-redirect-from

jekyll_get:
  data: collections
  json: 'http://api.georeferencer.com/repositories.json'
  cache: false
